#ifndef CONFIG_H
#define CONFIG_H

// PIN MAPPING
#define PIN_ZMPT101B_OUT   34
#define PIN_ACS712_OUT     35
#define PIN_RELAY_IN       26
#define PIN_LCD_SDA        21
#define PIN_LCD_SCL        22

// LCD
#define LCD_I2C_ADDRESS    0x27
#define LCD_COLUMNS        16
#define LCD_ROWS           2

// RELAY - verify polarity with test/relay_test before trusting this
#define RELAY_ACTIVE_HIGH  1
#define RELAY_DEFAULT_STATE_OFF 1

// ADC / SAMPLING
#define ADC_RESOLUTION_BITS   12
#define ADC_REF_VOLTAGE       3.3f
#define SAMPLE_WINDOW_MS      200
#define SAMPLE_INTERVAL_US    200

// CALIBRATION CONSTANTS - PLACEHOLDERS ONLY, see docs/SENSOR_CALIBRATION.md
#define ZMPT_ADC_MIDPOINT_DEFAULT   2048
#define ACS_ADC_MIDPOINT_DEFAULT    2935
#define VOLTAGE_CALIBRATION_FACTOR  1.0f
#define CURRENT_CALIBRATION_FACTOR  1.0f

// ENERGY
#define ENERGY_SAVE_INTERVAL_MS  (5UL * 60UL * 1000UL)

// TIMING
#define LCD_UPDATE_INTERVAL_MS    1000
#define SENSOR_READ_INTERVAL_MS   1000
#define CLOUD_UPLOAD_INTERVAL_MS  15000
#define WIFI_RECONNECT_INTERVAL_MS 10000

// WI-FI - PLACEHOLDERS ONLY, do not commit real values
#define WIFI_SSID       "YOUR_WIFI_NAME"
#define WIFI_PASSWORD   "YOUR_WIFI_PASSWORD"
#define WIFI_CONNECT_TIMEOUT_MS  15000

// THINGSPEAK - PLACEHOLDERS ONLY
#define THINGSPEAK_ENABLED     1
#define THINGSPEAK_API_KEY     "YOUR_THINGSPEAK_WRITE_API_KEY"
#define THINGSPEAK_CHANNEL_ID  "YOUR_CHANNEL_ID"
#define THINGSPEAK_SERVER      "http://api.thingspeak.com/update"

// BLYNK - PLACEHOLDERS ONLY
#define BLYNK_ENABLED          0
#define BLYNK_TEMPLATE_ID      "YOUR_TEMPLATE_ID"
#define BLYNK_TEMPLATE_NAME    "YOUR_TEMPLATE_NAME"
#define BLYNK_AUTH_TOKEN       "YOUR_BLYNK_AUTH_TOKEN"

// SERIAL
#define SERIAL_BAUD_RATE   115200
#define DEBUG_SERIAL       1

#endif // CONFIG_H
